name: quickjs
on: workflow_dispatch

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: bellard/quickjs

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64

      - name: Build
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: quickjs
          path: ./
