name: quickjs
on: workflow_dispatch

env:
  REPOSITORY_PATH: ${{ github.workspace }}/${{ github.sha }}

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: >-
            make
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-toolchain

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: bellard/quickjs

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPOSITORY_PATH }}

      - name: Build
        run: |
          cp $REPOSITORY_PATH/quickjs/CMakeLists.txt ./CMakeLists.txt
          cmake -B ./build
          cmake --build ./build
          mkdir ./out
          cp ./quickjs.h ./out/quickjs.h
          cp ./build/libquickjs.dll ./out/quickjs.dll
          cp ./build/libquickjs.lib ./out/quickjs.lib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quickjs-windows
          path: ./out/*

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: bellard/quickjs

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPOSITORY_PATH }}

      - name: Build
        run: |
          cp $REPOSITORY_PATH/quickjs/CMakeLists.txt ./CMakeLists.txt
          cmake -B ./build
          cmake --build ./build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quickjs-linux
          path: ./*

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: bellard/quickjs

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPOSITORY_PATH }}

      - name: Build
        run: |
          cp $REPOSITORY_PATH/quickjs/CMakeLists.txt ./CMakeLists.txt
          cmake -B ./build
          cmake --build ./build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quickjs-macos
          path: ./*
